# ────────────────────────────────────────────────────────────────
#  __  __                         _           _   
# |  \/  |_   _   _ __  _ __ ___ (_) ___  ___| |_ 
# | |\/| | | | | | '_ \| '__/ _ \| |/ _ \/ __| __|
# | |  | | |_| | | |_) | | | (_) | |  __/ (__| |_ 
# |_|  |_|\__, | | .__/|_|  \___// |\___|\___|\__|
#         |___/  |_|           |__/               
#  Welcome to the your project! 🚀
#  Here are the dependencies to make your project work!
# ────────────────────────────────────────────────────────────────

name: env_my_project

channels:
 - default
 - conda
 - conda-main
 - conda-forge

dependencies:
  - python=3.11
  - pip
  - pip:
    - -r requirements.txt
